INSERT INTO public.PRODUCT_REVIEW( ID, PRODUCT_REVIEW, REVIEW_DATE, ID_PRODUCT_REVIEW, ID_USERS) VALUES (	1	,'hello', now(), 1, 6);
INSERT INTO public.PRODUCT_REVIEW( ID, PRODUCT_REVIEW, REVIEW_DATE, ID_PRODUCT_REVIEW, ID_USERS) VALUES (	2	,'hi', now(), 	3, 2);
INSERT INTO public.PRODUCT_REVIEW( ID, PRODUCT_REVIEW, REVIEW_DATE, ID_PRODUCT_REVIEW, ID_USERS) VALUES (	3	,'what are you doing?', now(), 	5, 4);
INSERT INTO public.PRODUCT_REVIEW( ID, PRODUCT_REVIEW, REVIEW_DATE, ID_PRODUCT_REVIEW, ID_USERS) VALUES (	4	,'say my name?', now(), 4, 5);
INSERT INTO public.PRODUCT_REVIEW( ID, PRODUCT_REVIEW, REVIEW_DATE, ID_PRODUCT_REVIEW, ID_USERS) VALUES (	5	,'good bye', now(), 	7, 2);
INSERT INTO public.PRODUCT_REVIEW( ID, PRODUCT_REVIEW, REVIEW_DATE, ID_PRODUCT_REVIEW, ID_USERS) VALUES (	6	,'good morning', now(), 	7, 3);
INSERT INTO public.PRODUCT_REVIEW( ID, PRODUCT_REVIEW, REVIEW_DATE, ID_PRODUCT_REVIEW, ID_USERS) VALUES (	7	,'whatsapp ?', now(), 	6, 1);